/**
 * generated by Xtext unspecified
 */
package org.xtext.scripting.scripting;

import org.eclipse.xtext.mbase.XBlockExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Script</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.scripting.scripting.ScriptingPackage#getScript()
 * @model
 * @generated
 */
public interface Script extends XBlockExpression
{
} // Script
