/*
 * generated by Xtext unspecified
 */
package org.xtext.scripting.ui.quickfix;

import org.eclipse.xtext.mbase.ui.quickfix.MbaseQuickfixProvider;

public class ScriptingQuickfixProvider extends MbaseQuickfixProvider {
}
