/*
 * generated by Xtext unspecified
 */
package org.xtext.scripting.scoping;

import org.eclipse.xtext.mbase.scoping.batch.MbaseBatchScopeProvider;

public class ScriptingScopeProvider extends MbaseBatchScopeProvider {
}
