/*
 * generated by Xtext unspecified
 */
package org.xtext.scripting.scoping;

import org.eclipse.xtext.mbase.scoping.MbaseScopeProvider;

public class ScriptingScopeProvider extends MbaseScopeProvider {
}
