/*******************************************************************************
 * Copyright (c) 2012 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 ******************************************************************************/
grammar org.xtext.scripting.Scripting with org.eclipse.xtext.mbase.Mbase

generate scripting "http://www.xtext.org/scripting/Scripting"
//import "http://www.eclipse.org/xtext/mbase/Mbase"
//import "platform:/resource/org.eclipse.xtext.mbase/model/Mbase.ecore" as mbase
import "http://www.eclipse.org/xtext/mbase/Mbase" as mbase

Script returns mbase::XBlockExpression:
	{Script}
	(expressions+=XExpressionOrVarDeclaration ';'?)*;